version: "3.3"
services:
 apaches-server:
   image: httpd:latest
   networks:
      br02:
        ipv4_address: 10.1.0.10
   ports:
     - 80:80
   volumes:
     - apache-servidor:/usr/local/apache2/conf
 kasmweb-cliente:
   image: kasmweb/desktop:1.10.0-rolling
   networks:
      br02:
        ipv4_address: 10.1.0.20
   ports:
    - 6901:6901
   environment:
    - VNC_PW=password 
   stdin_open: true  # docker run -i
   tty: true         # docker run -t
   dns: 
    - 10.1.0.254
volumes:
 apache-servidor:
   external: true
networks:
  br02: 
    external: true